program: jax_run_mnist.py
name: mnist_uniform_T
method: grid
metric:
  goal: maximize
  name: lppd_valid
parameters:
  curve_params:
    parameters:
      k:
        values: [2, 5, 10, 20]
      activation:
        value: "relu"
      n_samples:
        value: 1
      lr:
        value: 0.005
      num_epochs:
        value: 50
      small_cnn:
        value: False
      batch_size:
        value: 480
      uniform_t_optimize:
        value: True
  sampling:
    parameters:
      space_config:
        values: 
          - {space: "lambda",
             prior_scale: 0.5,
             tube_scale: 0.1,
             epsilon: 25.0,
             prior_correct: False }
          # - {space: "lambda",
          #    prior_scale: 0.5,
          #    tube_scale: 0.1,
          #    epsilon: 25.0,
          #    prior_correct: True }
      num_chains:
        value: 10
      temperature:
        values: [500., 100.0, 50., 10., 1.]
      num_warmup:
        value: 500
      num_draws:
        value: 500
      sampler:
        values: ["mclmc",]
  rng_seed:
    values: [0,1,2,3,4]
  nuts_sweep_id:
    value: 10
    