program: jax_sub_sampling_from_path.py
name: toy_reg_vol_vs_tunnel_v2
method: grid
metric:
  goal: minimize
  name: r_hat_max
parameters:
  curve_params:
    parameters:
      k:
        values: [2, 4, 7, 10, 20]
      model_kwargs:
        parameters:
          depth:
            value: 3
          width:
            value: 16
          activation:
            values: ["relu", "elu",]
      n_samples:
        value: 20
      lr:
        value: 0.001
      num_epochs:
        value: 100_000
      use_validation:
        value: True
      out_scale:
        value: .05
      optimize_distparams:
        value: True
      uniform_t_optimize:
        values: [True, False]
  sampling:
    parameters:
      space_config:
        values: 
          - {space: "lambda",
             prior_scale: 0.5,
             tube_scale: 0.1,
             epsilon: 25.0,
             prior_correct: False }
          - {space: "varphi",
             prior_scale: 1.}
      num_chains:
        value: 10
      temperature:
        values: [1., 3.16227766, 10., 31.6227766, 100., 316.22776602]
      num_warmup:
        value: 1000
      num_draws:
        value: 1000
      sampler:
        values: ["mclmc",]
      num_forward_passes:
        value: 100
  rng_seed:
    values: [10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
  path_sweep_id:
    # value: "ddold/subspace_toy_reg/paxv2kno"
    value: "ddold/subspace_toy_reg/u7vfztsz"
  dataset:
    value: "generate"
    